name: Lint and Test

on:
  push:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*', node]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 'lts/*'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm test
